Первая отправка на проверку
avalon-dev-j110/laboratornaya-rabota-no2-PolarDL pull request #1
Opened 2020-03-31 16:10 UTC by PolarDL

Тут должен быть комментарий

2020-04-05 19:58 UTC, KolosovKD requested changes

2020-04-05 19:58 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +
Вы можете использовать переменную типа **Shape**, тогда не будет необходимости хранить отдельно площадь самой большой фигуры и ее индекс в массиве.

2020-04-05 19:58 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        System.out.println("The shape with the largest area is: " + shapeArray[j] + ", its area is " + shapeArray[j].getArea());
У вас уже есть максимальная площадь в переменной **largestShapeArea**. Нет нужды повторно вызывать метод **getArea()**.

2020-04-05 19:58 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Circle.java
> +        this.radius = (float) Math.random() * 70;
Генерация значений в конструкторе не лучшая идея - вы не дали возможность определять значения полей вашего объекта при создании. Я не могу создать круг заданного радиуса, я всегда получаю круг со случайным радиусом.
Стоит передавать радиус в конструктор в качестве аргумента, а генерировать само значение там, где вызывается конструктор.

2020-04-05 19:58 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/PointImpl.java
> +        this.xCoordinate = (float) Math.random() * 100;
Пусть значения передатся при взове конструктора, а генератор случайных чисел их генерирует там, где вы вызываете конктруктор. Это будет больше похоже на реальный код.

2020-04-06 09:49 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +        System.out.println("The shape with the largest area is: " + shapeArray[j] + ", its area is " + shapeArray[j].getArea());
Да, зря лишний раз вызвал метод. Исправлю.

2020-04-06 09:56 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/shapes/Circle.java
> +        this.radius = (float) Math.random() * 70;
Про генерацию значений в конструкторе - да, это абсолютно неприемлемо, если нам надо создать фигуру с заданными геометрическими параметрами.
То есть в данном случае вы хотите, чтобы я переделал конструктор круга, чтобы при создании указывать радиус? Ок, сделаю.

2020-04-06 10:01 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/shapes/PointImpl.java
> +        this.xCoordinate = (float) Math.random() * 100;
Правильно ли я понял, что вы хотите, чтобы я переписал конструктор PointImpl в виде:
`public PointImpl (float xCoordinate, float yCoordinate) {
        this.xCoordinate = xCoordinate;
        this.yCoordinate = yCoordinate;
    }`
И создавал для каждой фигуры необходимые ей точки вызывая конструктор (и вот тут уже при вызове мог указать конкретные точки или сгенерировать случайные). 
Ну и, соответственно, необходимо изменить конструкторы всех фигур, удалив созданиее точек изнутри конструкторов.

2020-04-06 10:04 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +
То есть переписать тело метода **getLargestShape** так, чтобы оперировать переменной типа **Shape**, а не двумя отдельными переменными **float largestShapeArea** и **int j** ?
Ок, попробую

2020-04-08 21:10 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +
Тут либо-либо. Или хранить сразу Shape, или ниже не дергать второй раз метод **getArea**, а использовать значение из переменной **largestShapeArea**

2020-04-08 21:16 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/PointImpl.java
> +        this.xCoordinate = (float) Math.random() * 100;
Да, генерацию значений можно не убирать - генерация для демонстрации очень хорошее решение. Но сейчас у вас не рабочий код, пригодный только для демонстрации.
Если вы переделаете конструкторы фигур так, чтобы они принимали точки, а конструктор точки так, чтобы он принимал координаты, то вы сможете оставить генерацию значени в методе мэйн, где создаете объекты. Но классы будут абсолтно рабочими.

Создание четырехугольника будет выглядеть в методе main примено так:
`Shape rectangle = new Rectangle(
new PointImpl(Math.random(), Math.random())
new PointImpl(Math.random(), Math.random()));`

2020-04-09 10:01 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +
Использовать переменную **Shape** все-таки логичнее, чем плодить отдельно переменные для площади и индекса. Переделаю

2020-04-09 10:02 UTC, PolarDL commented on src/ru/avalon/java/dev/j10/labs/shapes/PointImpl.java
> +        this.xCoordinate = (float) Math.random() * 100;
Понял подход. Согласен. Обновлю

2020-04-18 08:13 UTC, merged